package com.returntrader.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.returntrader.database.CompanyItemInfo;
import com.returntrader.database.NotificationMeta;

import com.returntrader.database.CompanyItemInfoDao;
import com.returntrader.database.NotificationMetaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig companyItemInfoDaoConfig;
    private final DaoConfig notificationMetaDaoConfig;

    private final CompanyItemInfoDao companyItemInfoDao;
    private final NotificationMetaDao notificationMetaDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        companyItemInfoDaoConfig = daoConfigMap.get(CompanyItemInfoDao.class).clone();
        companyItemInfoDaoConfig.initIdentityScope(type);

        notificationMetaDaoConfig = daoConfigMap.get(NotificationMetaDao.class).clone();
        notificationMetaDaoConfig.initIdentityScope(type);

        companyItemInfoDao = new CompanyItemInfoDao(companyItemInfoDaoConfig, this);
        notificationMetaDao = new NotificationMetaDao(notificationMetaDaoConfig, this);

        registerDao(CompanyItemInfo.class, companyItemInfoDao);
        registerDao(NotificationMeta.class, notificationMetaDao);
    }
    
    public void clear() {
        companyItemInfoDaoConfig.clearIdentityScope();
        notificationMetaDaoConfig.clearIdentityScope();
    }

    public CompanyItemInfoDao getCompanyItemInfoDao() {
        return companyItemInfoDao;
    }

    public NotificationMetaDao getNotificationMetaDao() {
        return notificationMetaDao;
    }

}
