package com.returntrader.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTIFICATION_META".
*/
public class NotificationMetaDao extends AbstractDao<NotificationMeta, Long> {

    public static final String TABLENAME = "NOTIFICATION_META";

    /**
     * Properties of entity NotificationMeta.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property WebLink = new Property(3, String.class, "webLink", false, "WEB_LINK");
        public final static Property ImageLink = new Property(4, String.class, "imageLink", false, "IMAGE_LINK");
        public final static Property UpdatedAt = new Property(5, String.class, "updatedAt", false, "UPDATED_AT");
    }


    public NotificationMetaDao(DaoConfig config) {
        super(config);
    }
    
    public NotificationMetaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTIFICATION_META\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"CONTENT\" TEXT," + // 2: content
                "\"WEB_LINK\" TEXT," + // 3: webLink
                "\"IMAGE_LINK\" TEXT," + // 4: imageLink
                "\"UPDATED_AT\" TEXT);"); // 5: updatedAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTIFICATION_META\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NotificationMeta entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
 
        String webLink = entity.getWebLink();
        if (webLink != null) {
            stmt.bindString(4, webLink);
        }
 
        String imageLink = entity.getImageLink();
        if (imageLink != null) {
            stmt.bindString(5, imageLink);
        }
 
        String updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindString(6, updatedAt);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NotificationMeta entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
 
        String webLink = entity.getWebLink();
        if (webLink != null) {
            stmt.bindString(4, webLink);
        }
 
        String imageLink = entity.getImageLink();
        if (imageLink != null) {
            stmt.bindString(5, imageLink);
        }
 
        String updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindString(6, updatedAt);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NotificationMeta readEntity(Cursor cursor, int offset) {
        NotificationMeta entity = new NotificationMeta( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // webLink
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // imageLink
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // updatedAt
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NotificationMeta entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setWebLink(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setImageLink(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUpdatedAt(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NotificationMeta entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NotificationMeta entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NotificationMeta entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
